version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      vue-ecosystem:
        patterns:
          - "vue"
          - "@vue/*"
          - "vue-router"
          - "vue-tsc"
          - "@vitejs/plugin-vue"
          - "@vue/language-core"

      state-and-utils:
        patterns:
          - "pinia"
          - "@vueuse/core"
          - "gsap"

      ui-libraries:
        patterns:
          - "bootstrap"
          - "vuetify"
          - "sass-embedded"

      dev-tools:
        patterns:
          - "vite"
          - "eslint"
          - "prettier"
          - "@rushstack/eslint-patch"
          - "npm-run-all"
          - "@tsconfig/node18"
          - "@types/node"
          - "@vue/eslint-config-prettier"
          - "@vue/eslint-config-typescript"
          - "@vue/tsconfig"
      typescript:
        patterns:
          - "typescript"
      http-and-deploy:
        patterns:
          - "axios"
          - "gh-pages"