version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" # Frequency of checks
    open-pull-requests-limit: 3
    groups:
      vue-and-vuetify:
        patterns:
          - "vue"
          - "vuetify"
      gsap:
        patterns:
          - "gsap"
      pinia:
        patterns:
          - "pinia"
      vue-use:
        patterns:
          - "@vueuse/*"
      typescript:
        patterns:
          - "typescript"