version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" # Frequency of checks
    open-pull-requests-limit: 1 # Limit to a single open PR
    groups:
      all-updates:
        patterns:
          - "*" # Match all dependencies
